/*
 파일명 : mockData.ts
 작성일 : 2026-05-04
 작성자 : 김호성
 수정내역 : 초기등록
*/
import type { Trip } from '../types/trip.types';
import type { BlogPost, ChatRoom, Place, Challenge } from '../types/common.types';
import type { User } from '../types/auth.types';

export const MOCK_USER: User = {
  id: 'user1',
  email: 'moment@example.com',
  nickname: '여행자 김모먼',
  profileImage: 'https://i.pravatar.cc/150?img=12',
  bio: '세상의 모든 순간을 담고 싶어요 ✈️',
  followersCount: 248,
  followingCount: 132,
  tripsCount: 17,
  createdAt: '2024-01-01',
};

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip1',
    title: '오사카 봄 여행 🌸',
    destination: '일본 오사카',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    startDate: '2026-05-10',
    endDate: '2026-05-14',
    status: 'upcoming',
    members: [
      { id: 'user1', nickname: '김모먼', profileImage: 'https://i.pravatar.cc/150?img=12', role: 'owner' },
      { id: 'user2', nickname: '이여행', profileImage: 'https://i.pravatar.cc/150?img=5', role: 'member' },
      { id: 'user3', nickname: '박설렘', profileImage: 'https://i.pravatar.cc/150?img=8', role: 'member' },
    ],
    days: [
      {
        date: '2026-05-10',
        dayNumber: 1,
        schedules: [
          { id: 's1', time: '10:00', title: '간사이 공항 도착', description: '입국 심사 및 환전', duration: 120 },
          { id: 's2', time: '13:00', title: '도톤보리 점심', description: '타코야키, 오코노미야끼', place: { id: 'p1', name: '도톤보리', address: '오사카 중구', latitude: 34.6687, longitude: 135.5009, category: '음식' }, duration: 90 },
          { id: 's3', time: '15:00', title: '오사카성 관광', place: { id: 'p2', name: '오사카성', address: '오사카 중구 오사카성', latitude: 34.6873, longitude: 135.5262, category: '역사' }, duration: 120 },
          { id: 's4', time: '19:00', title: '신사이바시 쇼핑', duration: 120 },
        ],
      },
      {
        date: '2026-05-11',
        dayNumber: 2,
        schedules: [
          { id: 's5', time: '09:00', title: '유니버설 스튜디오 재팬', duration: 480 },
          { id: 's6', time: '20:00', title: '난바 야시장', duration: 120 },
        ],
      },
    ],
    checklist: [
      { id: 'c1', title: '여권 확인', category: '서류', isCompleted: true },
      { id: 'c2', title: '항공권 프린트', category: '서류', isCompleted: true },
      { id: 'c3', title: '엔화 환전', category: '금융', isCompleted: false },
      { id: 'c4', title: '포켓 와이파이 예약', category: '통신', isCompleted: false },
      { id: 'c5', title: '여행자 보험 가입', category: '보험', isCompleted: false },
      { id: 'c6', title: '호텔 확인증 출력', category: '숙박', isCompleted: true },
      { id: 'c7', title: '상비약 챙기기', category: '건강', isCompleted: false },
    ],
    totalBudget: 1500000,
    description: '오사카에서 즐기는 봄 벚꽃 여행',
    createdAt: '2026-04-01',
  },
  {
    id: 'trip2',
    title: '제주 힐링 여행 🌊',
    destination: '제주도',
    coverImage: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
    startDate: '2026-03-20',
    endDate: '2026-03-23',
    status: 'completed',
    members: [
      { id: 'user1', nickname: '김모먼', profileImage: 'https://i.pravatar.cc/150?img=12', role: 'owner' },
    ],
    days: [],
    checklist: [],
    totalBudget: 500000,
    createdAt: '2026-03-01',
  },
  {
    id: 'trip3',
    title: '방콕 & 파타야 여름 휴가 🏖️',
    destination: '태국',
    coverImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    startDate: '2026-07-20',
    endDate: '2026-07-28',
    status: 'upcoming',
    members: [
      { id: 'user1', nickname: '김모먼', profileImage: 'https://i.pravatar.cc/150?img=12', role: 'owner' },
      { id: 'user2', nickname: '이여행', profileImage: 'https://i.pravatar.cc/150?img=5', role: 'member' },
    ],
    days: [],
    checklist: [],
    totalBudget: 2000000,
    createdAt: '2026-04-15',
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog1',
    authorId: 'user2',
    authorName: '이여행',
    authorImage: 'https://i.pravatar.cc/150?img=5',
    content: '교토의 아라시야마 대나무 숲을 걸었어요 🎋 이른 아침 안개 속에 펼쳐진 대나무 숲이 너무 신비로웠습니다. 인생샷 건졌어요!',
    images: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    ],
    location: '일본 교토',
    tags: ['교토', '아라시야마', '일본여행'],
    likes: 142,
    comments: 23,
    isLiked: true,
    visibility: 'public',
    createdAt: '2026-04-28T08:30:00Z',
  },
  {
    id: 'blog2',
    authorId: 'user3',
    authorName: '박설렘',
    authorImage: 'https://i.pravatar.cc/150?img=8',
    content: '바르셀로나 가우디 건축물 투어 완료! 사그라다 파밀리아는 정말 압도적이었어요. 100년이 넘는 건축 역사가 느껴지는 곳 ⛪',
    images: [
      'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
    ],
    location: '스페인 바르셀로나',
    tags: ['바르셀로나', '가우디', '스페인여행'],
    likes: 89,
    comments: 15,
    isLiked: false,
    visibility: 'public',
    createdAt: '2026-04-26T14:20:00Z',
  },
  {
    id: 'blog3',
    authorId: 'user4',
    authorName: '최순간',
    authorImage: 'https://i.pravatar.cc/150?img=15',
    content: '제주 협재 해변의 노을 🌅 물이 너무 맑아서 스노클링도 했어요. 제주는 올 때마다 새로운 느낌이에요.',
    images: [
      'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ],
    location: '제주도 협재',
    tags: ['제주', '협재해변', '국내여행'],
    likes: 203,
    comments: 41,
    isLiked: false,
    visibility: 'public',
    createdAt: '2026-04-24T18:00:00Z',
  },
];

export const MOCK_CHAT_ROOMS: ChatRoom[] = [
  {
    id: 'chat1',
    name: '오사카 여행자 모임',
    type: 'location',
    lastMessage: '오사카 도톤보리 맛집 알려주세요~',
    lastMessageTime: '10분 전',
    unreadCount: 3,
    members: 24,
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=200',
    location: '일본 오사카',
  },
  {
    id: 'chat2',
    name: '오사카 봄 여행 💬',
    type: 'trip',
    lastMessage: '이여행: 내일 집합 시간 10시 맞죠?',
    lastMessageTime: '1시간 전',
    unreadCount: 0,
    members: 3,
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=200',
    location: '일본 오사카',
  },
  {
    id: 'chat3',
    name: '제주 여행자들',
    type: 'location',
    lastMessage: '협재 해변 캠핑 가실 분!',
    lastMessageTime: '어제',
    unreadCount: 7,
    members: 156,
    thumbnail: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=200',
    location: '제주도',
  },
];

export const MOCK_PLACES: Place[] = [
  {
    id: 'place1',
    name: '도톤보리',
    category: '음식',
    address: '일본 오사카 중앙구 도톤보리',
    latitude: 34.6687,
    longitude: 135.5009,
    rating: 4.5,
    reviewCount: 1240,
    distance: 0.3,
    images: ['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800'],
    description: '오사카 최고의 음식 거리. 타코야키, 오코노미야끼, 구시카츠 등 다양한 오사카 명물을 맛볼 수 있습니다.',
    openHours: '24시간',
  },
  {
    id: 'place2',
    name: '오사카성',
    category: '역사',
    address: '일본 오사카 중앙구 오사카성',
    latitude: 34.6873,
    longitude: 135.5262,
    rating: 4.3,
    reviewCount: 3560,
    distance: 1.2,
    images: ['https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800'],
    description: '도요토미 히데요시가 축성한 일본의 대표적인 성. 오사카의 역사와 문화를 느낄 수 있는 곳입니다.',
    openHours: '09:00 - 17:00',
  },
  {
    id: 'place3',
    name: '신사이바시',
    category: '쇼핑',
    address: '일본 오사카 중앙구 신사이바시',
    latitude: 34.6720,
    longitude: 135.5010,
    rating: 4.2,
    reviewCount: 892,
    distance: 0.5,
    images: ['https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800'],
    description: '오사카 최대의 쇼핑 거리. 유명 브랜드부터 로컬 숍까지 다양한 쇼핑을 즐길 수 있습니다.',
    openHours: '11:00 - 21:00',
  },
  {
    id: 'place4',
    name: '아라시야마',
    category: '자연',
    address: '일본 교토 우쿄구 아라시야마',
    latitude: 35.0094,
    longitude: 135.6726,
    rating: 4.7,
    reviewCount: 5120,
    distance: 3.8,
    images: ['https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800'],
    description: '교토의 대표 관광지. 대나무 숲, 도게쓰교, 천룡사 등을 즐길 수 있습니다.',
    openHours: '24시간',
  },
];

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'ch1',
    title: '첫 해외여행',
    description: '첫 해외 여행을 다녀오세요!',
    condition: '해외 여행 1회 완료',
    badgeImage: '✈️',
    badgeColor: '#FF6B35',
    isCompleted: true,
    progress: 1,
    maxProgress: 1,
    category: '여행',
    completedAt: '2024-03-15',
    icon: '✈️',
    currentCount: 1,
    targetCount: 1,
    rewardPoints: 100,
  },
  {
    id: 'ch2',
    title: '아시아 탐험가',
    description: '아시아 5개국을 여행하세요',
    condition: '아시아 국가 5개국 방문',
    badgeImage: '🌏',
    badgeColor: '#10B981',
    isCompleted: false,
    progress: 3,
    maxProgress: 5,
    category: '여행',
    icon: '🌏',
    currentCount: 3,
    targetCount: 5,
    rewardPoints: 500,
  },
  {
    id: 'ch3',
    title: '사진작가',
    description: '여행 기록 사진 100장 이상 업로드',
    condition: '사진 100장 업로드',
    badgeImage: '📸',
    badgeColor: '#3B82F6',
    isCompleted: false,
    progress: 67,
    maxProgress: 100,
    category: '기록',
    icon: '📸',
    currentCount: 67,
    targetCount: 100,
    rewardPoints: 300,
  },
  {
    id: 'ch4',
    title: '소셜 트래블러',
    description: '친구 5명과 함께 여행',
    condition: '공동 여행 5회 완료',
    badgeImage: '👥',
    badgeColor: '#8B5CF6',
    isCompleted: true,
    progress: 5,
    maxProgress: 5,
    category: '소셜',
    completedAt: '2025-08-20',
    icon: '👥',
    currentCount: 5,
    targetCount: 5,
    rewardPoints: 400,
  },
  {
    id: 'ch5',
    title: '맛집 헌터',
    description: '음식 카테고리 기록 50개 달성',
    condition: '음식 관련 기록 50개',
    badgeImage: '🍜',
    badgeColor: '#F59E0B',
    isCompleted: false,
    progress: 28,
    maxProgress: 50,
    category: '음식',
    icon: '🍜',
    currentCount: 28,
    targetCount: 50,
    rewardPoints: 200,
  },
  {
    id: 'ch6',
    title: '만 보 여행자',
    description: '여행 중 하루 만 보 걷기',
    condition: '하루 10,000보 달성',
    badgeImage: '👟',
    badgeColor: '#EF4444',
    isCompleted: true,
    progress: 1,
    maxProgress: 1,
    category: '건강',
    completedAt: '2025-11-12',
    icon: '👟',
    currentCount: 1,
    targetCount: 1,
    rewardPoints: 150,
  },
];

export const MOCK_RECOMMENDED_PLACES = [
  { id: 'r1', name: '경복궁', city: '서울', image: 'https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=400', rating: 4.6, category: '역사' },
  { id: 'r2', name: '해운대 해수욕장', city: '부산', image: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=400', rating: 4.4, category: '자연' },
  { id: 'r3', name: '한라산', city: '제주', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', rating: 4.8, category: '자연' },
  { id: 'r4', name: '전주 한옥마을', city: '전주', image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=400', rating: 4.5, category: '역사' },
  { id: 'r5', name: '남이섬', city: '춘천', image: 'https://images.unsplash.com/photo-1534166172072-c02db6f78b8a?w=400', rating: 4.3, category: '자연' },
];
